config/routes.rb
PhusionCMS::Application.routes.draw do |map|
  resources :events

  

  
  root :to => 'nodes#index'
  resources :nodes
  
  #  scope ':shortcut' do
  resources :link_list_elems, :except => [:index, :destroy] do
    resources :links, :except => [:index, :show, :destroy] do
      post :file, :on => :member
    end
  end
  resources :text_elems, :except => [:index, :destroy]
  resources :elements, :only => [:destroy] do
    get :move, :on => :member
  end
  resources :blog_elems, :except => [:index, :destroy]
  resources :photo_gallery_elems, :except => [:index, :destroy] do
    resources :photos, :except => [:index, :show]
  end
  resources :calendar_elems, :except => [:index, :destroy] do
    resources :events, :except => [:index]
  end
#  match '/calendar_elems/:id(/:year(/:month))' => 'calendar_elems#show', :as => :calendar_elems, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  #  end

  # Elements resources
  match ':shortcut/:position/new_element' => 'templates#new_element', :as => :new_element

  # shortcut usage
  match ':shortcut' => 'templates#show', :as => :shortcut
  match 'admin/:shortcut' => 'templates#edit', :as => :admin_shortcut
end

app/models/calendar_elem.rb
class CalendarElem < ActiveRecord::Base
  has_one :element, :as => :elem
  has_many :events

  DISPLAY_STYLES = [
    'Calendar',
    'Event List'
  ]

  def self.display_style_select
    DISPLAY_STYLES
  end

end

app/controllers/calendar_elems_controller.rb
class CalendarElemsController < ApplicationController
  before_filter :get_template
  
  def show
    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i
    @shown_month = Date.civil(@year, @month) 
    @event_strips = Event.event_strips_for_month(@shown_month)
  end

  def edit
    @element = @calendar_elem.element
  end

  def new
    @element = Element.new(:position => params[:position], :column_order => Element.set_highest_column_order(params[:position]))
    @calendar_elem = @element.elem = CalendarElem.new
  end

  def create
    @element = Element.new(:position => params[:position], :column_order => params[:column_order])
    @calendar_elem = @element.elem = CalendarElem.new(params[:calendar_elem])
    if @calendar_elem.save and @element.save and @node.template.elements << @element
      redirect_to calendar_elem_path(@calendar_elem, :notice => "Calendar Element successfully created.")
    else
      render :action => 'new'
    end
  end

  def update
    @element = @calendar_elem.element
    if @calendar_elem.update_attributes(params[:calendar_elem])
      redirect_to @calendar_elem, :notice => "Calendar Element successfully updated."
    else
      render :action => 'edit'
    end
  end


  private
  
  def get_template
    if params[:id]
      @calendar_elem = CalendarElem.find(params[:id])
      @node = @calendar_elem.element.template.node
    end
    super
  end


  
end

app/helpers/calendar_elems_helper.rb
module CalendarElemsHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts(calendar_elem)
    yr = ( @year ? @year : Time.zone.now.year).to_i
    mnth = ( @month ? @month : Time.zone.now.month).to_i
    shown_month = ( @shown_month ? @shown_month : Date.civil( yr, mnth ))
    event_strips = ( @event_strips ? @event_strips : Event.event_strips_for_month(shown_month))
    return {
      :year => yr,
      :month => mnth,
      :event_strips => event_strips,
      :month_name_text => I18n.localize(shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(shown_month.prev_month),
      :next_month_text => month_link(shown_month.next_month) + " >>",
      :use_all_day => true
    }
  end

  def event_calendar(calendar_elem)
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts(calendar_elem) do |args|
      event, day = args[:event], args[:day]
      html = %(<a href="#{calendar_elem_event_path(event.calendar_elem, event.id)}" title="#{h(event.name)}">)
      html << display_event_time(event, day)
      html << %(#{h(event.name)}</a>)
      html
    end
  end
end

app/views/calendar_elems/_form.html.erb
<%= form_for(@calendar_elem)  do |f| %>
  <% if @calendar_elem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize((@calendar_elem.errors.count ), "error") %> prohibited this element from being saved:</h2>
      <ul>
        <% @calendar_elem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %> &nbsp;
    <%= f.check_box :display_title %>
    <%= f.label :display_title %>
  </div>
  <div class="field">
    <%= f.label :display_style %><br />
    <%= f.select :display_style, CalendarElem.display_style_select %>
  </div>
  <div class="field">
    <%= f.label :event_color %><br />
    <%= f.select :event_color, color_select %>
  </div>
  <div class="field">
    <%= f.label :background_color %><br />
    <%= f.select :background_color, color_select %>
  </div>


  <%= hidden_field_tag :column_order, @element.column_order %>
  <%= hidden_field_tag :position, @element.position %>
  <%= hidden_field_tag :shortcut, @shortcut %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendar_elems/_show.html.erb
<% calendar_elem = locals[:elem] %>

<div class="calendar-elem">
  <h3><%= calendar_elem.title if calendar_elem.display_title %></h3>
  <%=raw event_calendar(calendar_elem) %>
</div>

app/views/calendar_elems/edit.html.erb
<h1>Options for Calendar Element</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @calendar_elem %>

app/views/calendar_elems/new.html.erb
<h1>New Calendar Element</h1>

<%= render 'form' %>

<%= link_to 'Cancel', shortcut_path(@shortcut) %>

app/views/calendar_elems/show.html.erb
<h1>Calendar Element</h1>

<%= render 'show', :locals => {:elem => @calendar_elem} %>


<%= admin_area do %>
  <p>
    | <%= link_to 'Add Event', new_calendar_elem_event_path(@calendar_elem) %> |
    <%= link_to 'Calendar Options', edit_calendar_elem_path(@calendar_elem) %> |
    <%= link_to 'Done', shortcut_path(@shortcut) %> |
  </p>
<% end %>