config/routes.rb
PhusionCMS::Application.routes.draw do |map|
  resources :events

  

  
  root :to => 'nodes#index'
  resources :nodes
  
  #  scope ':shortcut' do
  resources :link_list_elems, :except => [:index, :destroy] do
    resources :links, :except => [:index, :show, :destroy] do
      post :file, :on => :member
    end
  end
  resources :text_elems, :except => [:index, :destroy]
  resources :elements, :only => [:destroy] do
    get :move, :on => :member
  end
  resources :blog_elems, :except => [:index, :destroy]
  resources :photo_gallery_elems, :except => [:index, :destroy] do
    resources :photos, :except => [:index, :show]
  end
  resources :calendar_elems, :except => [:index, :destroy] do
    resources :events, :except => [:index]
  end
#  match '/calendar_elems/:id(/:year(/:month))' => 'calendar_elems#show', :as => :calendar_elems, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  #  end

  # Elements resources
  match ':shortcut/:position/new_element' => 'templates#new_element', :as => :new_element

  # shortcut usage
  match ':shortcut' => 'templates#show', :as => :shortcut
  match 'admin/:shortcut' => 'templates#edit', :as => :admin_shortcut
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :node
  has_many :nodes, :dependent => :nullify
  has_one :template, :dependent => :destroy

  accepts_nested_attributes_for :template 
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_filter :get_home_node
  before_filter :home_form?, :only => [:new, :edit, :create, :update]
  # GET /nodes
  # GET /nodes.xml
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.xml
  def show
    @node = Node.find(params[:id]) if params[:id]
    redirect_to shortcut_path(@node.shortcut)
  rescue URI::InvalidURIError:
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.xml
  def new
    @node = Node.new(:displayed => true)
    @node.template = Template.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
    @node.template = Template.new unless @node.template
  end

  # POST /nodes
  # POST /nodes.xml
  def create
    @node = Node.new(params[:node])
  
    respond_to do |format|
      if @node.save
        format.html { redirect_to(@node, :notice => 'Node was successfully created.') }
        format.xml  { render :xml => @node, :status => :created, :location => @node }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.xml
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to(@node, :notice => 'Node was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.xml
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to(nodes_url) }
      format.xml  { head :ok }
    end
  end

  
  def home_form?
    @home_form = false
    @home_form = true if params[:id] and @home_node.id == params[:id]
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? or @node.template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize((@node.errors.count + @node.template.errors.count), "error") %> prohibited this node from being saved:</h2>
      <ul>
        <% @node.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        <% @node.template.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @home_form %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :menu_name %><br />
      <%= f.text_field :menu_name %>
    </div>
    <div class="field">
      <%= f.label :shortcut %><br />
      http://localhost/<%= f.text_field :shortcut %>
    </div>
    <div class="field">
      <%= f.check_box :displayed, :checked => true %>
      <%= f.label :displayed, "Display Page?" %>
    </div>
    <div class="field">
      <%= f.label :node_id, "Where Should This Page Go?" %><br/>
      <%= f.select :node_id, options_for_select([[@home_node.menu_name,@home_node.id]] + options_tree_recursive(@home_node, ""), "Home") %>
    </div>

  <% else %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, :disabled => 'disabled' %>
    </div>

    <div class="field">
      <%= f.label :menu_name %><br />
      <%= f.text_field :menu_name, :disabled => 'disabled'  %>
    </div>
    <div class="field">
      <%= f.label :shortcut %><br />
      http://localhost/<%= f.text_field :shortcut, :disabled => 'disabled'  %>
    </div>
    <div class="field">
      <%= f.check_box :displayed, :checked => true, :disabled => 'disabled'  %>
      <%= f.label :displayed, "Display Page?" %>
    </div>

    <%= f.hidden_field :title %>
    <%= f.hidden_field :displayed %>
    <%= f.hidden_field :menu_name %>
    <%= f.hidden_field :shortcut %>

  <% end %>



  <%= f.fields_for :template do |tf| %>
    <div class="field">
      <%= tf.label :template_name, "Template Type" %><br />
      <%= tf.select :template_name, ['Right Inside','Home'] %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Menu name</th>
    <th>Shortcut</th>
    <th>Displayed</th>
  </tr>

  <% @nodes.each do |node| %>
    <tr>
      <td><%= node.title %></td>
      <td><%= node.menu_name %></td>
      <td><%= node.shortcut %></td>
      <td><%= node.displayed %></td>
      <td><%= link_to 'Show', node %></td>
      <td><%= link_to 'Edit', edit_node_path(node) %></td>
      <td><%= link_to 'Destroy', node, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>


<p>
  <%=raw display_menu_list() %>
</p>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p>
  <b>Title:</b>
  <%= @node.title %>
</p>

<p>
  <b>Menu name:</b>
  <%= @node.menu_name %>
</p>

<p>
  <b>Shortcut:</b>
  <%= @node.shortcut %>
</p>

<p>
  <b>Displayed:</b>
  <%= @node.displayed %>
</p>

<% if @template %>
  <p>
    <b>Template Name</b>
    <%= @template.template_name %>
  </p>
<% end %>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>