config/routes.rb
PhusionCMS::Application.routes.draw do |map|
  resources :events

  

  
  root :to => 'nodes#index'
  resources :nodes
  
  #  scope ':shortcut' do
  resources :link_list_elems, :except => [:index, :destroy] do
    resources :links, :except => [:index, :show, :destroy] do
      post :file, :on => :member
    end
  end
  resources :text_elems, :except => [:index, :destroy]
  resources :elements, :only => [:destroy] do
    get :move, :on => :member
  end
  resources :blog_elems, :except => [:index, :destroy]
  resources :photo_gallery_elems, :except => [:index, :destroy] do
    resources :photos, :except => [:index, :show]
  end
  resources :calendar_elems, :except => [:index, :destroy] do
    resources :events, :except => [:index]
  end
#  match '/calendar_elems/:id(/:year(/:month))' => 'calendar_elems#show', :as => :calendar_elems, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  #  end

  # Elements resources
  match ':shortcut/:position/new_element' => 'templates#new_element', :as => :new_element

  # shortcut usage
  match ':shortcut' => 'templates#show', :as => :shortcut
  match 'admin/:shortcut' => 'templates#edit', :as => :admin_shortcut
end

app/models/photo_gallery_elem.rb
class PhotoGalleryElem < ActiveRecord::Base
  has_one :element, :as => :elem
  has_many :photos

  DISPLAY_STYLES = [
    'Thumbnail',
    'Thumbnail + Caption',
    'Slideshow'
  ]

  def self.display_style_select
    DISPLAY_STYLES
  end
end

app/controllers/photo_gallery_elems_controller.rb
class PhotoGalleryElemsController < ApplicationController
  before_filter :get_template


  def show
  end

  def new
    @element = Element.new(:position => params[:position], :column_order => Element.set_highest_column_order(params[:position]))
    @photo_gallery_elem = @element.elem=PhotoGalleryElem.new
  end


  def edit
    @element = @photo_gallery_elem.element
  end


  def create
    @element = Element.new(:position => params[:position], :column_order => params[:column_order])
    @photo_gallery_elem = @element.elem = PhotoGalleryElem.new(params[:photo_gallery_elem])
    if @photo_gallery_elem.save and @element.save and @node.template.elements << @element
      redirect_to photo_gallery_elem_path(@photo_gallery_elem, :notice => "Blog Element successfully added!")
    else
      render :action => 'new'
    end
  end


  def update
    @element = @photo_gallery_elem.element
    if @photo_gallery_elem.update_attributes(params[:photo_gallery_elem])
      redirect_to photo_gallery_elem_path(@photo_gallery_elem, :notice => "Blog Element successfully updated!")
    else
      render :action => 'edit'
    end
  end


  private
  def get_template
    if params[:id]
      @photo_gallery_elem = PhotoGalleryElem.find(params[:id])
      @node = @photo_gallery_elem.element.template.node
    end
    super
  end


end

app/helpers/photo_gallery_elems_helper.rb
module PhotoGalleryElemsHelper
end

app/views/photo_gallery_elems/_form.html.erb
<%= form_for(@photo_gallery_elem) do |f| %>
  <% if @photo_gallery_elem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo_gallery_elem.errors.count, "error") %> prohibited this photo_gallery_elem from being saved:</h2>

      <ul>
        <% @photo_gallery_elem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %> &nbsp;
    <%= f.check_box :display_title %>
    <%= f.label :display_title %>
  </div>
  <div class="field">
    <%= f.label :display_style %><br />
    <%= f.select :display_style, PhotoGalleryElem.display_style_select %>
  </div>

  <%= hidden_field_tag :column_order, @element.column_order %>
  <%= hidden_field_tag :position, @element.position %>
  <%= hidden_field_tag :shortcut, @shortcut %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photo_gallery_elems/_show.html.erb
<% photo_gallery_elem = locals[:elem] %>

<div class="photo-gallery-elem">
  <h3><%= photo_gallery_elem.title if photo_gallery_elem.display_title %></h3>

  <% photo_gallery_elem.photos.each do |photo| %>
    <%= render 'photos/photo', :locals => {:photo => photo} %>
  <% end %>
 
</div>

app/views/photo_gallery_elems/edit.html.erb
<h1>Options for Photo Gallery Element</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @photo_gallery_elem %> 

app/views/photo_gallery_elems/new.html.erb
<h1>New Photo Gallery Element</h1>

<%= render 'form' %>

<%= link_to 'Cancel', shortcut_path(@shortcut) %>

app/views/photo_gallery_elems/show.html.erb
<%= render 'show', :locals => {:elem => @photo_gallery_elem} %>

<%= admin_area do %>
  <p>
    | <%= link_to 'Add Photo', new_photo_gallery_elem_photo_path(@photo_gallery_elem) %> |
    <%= link_to 'Gallery Options', edit_photo_gallery_elem_path(@photo_gallery_elem) %> |
    <%= link_to 'Done', shortcut_path(@shortcut) %> |
  </p>
<% end %>