config/routes.rb
PhusionCMS::Application.routes.draw do |map|
  resources :events

  

  
  root :to => 'nodes#index'
  resources :nodes
  
  #  scope ':shortcut' do
  resources :link_list_elems, :except => [:index, :destroy] do
    resources :links, :except => [:index, :show, :destroy] do
      post :file, :on => :member
    end
  end
  resources :text_elems, :except => [:index, :destroy]
  resources :elements, :only => [:destroy] do
    get :move, :on => :member
  end
  resources :blog_elems, :except => [:index, :destroy]
  resources :photo_gallery_elems, :except => [:index, :destroy] do
    resources :photos, :except => [:index, :show]
  end
  resources :calendar_elems, :except => [:index, :destroy] do
    resources :events, :except => [:index]
  end
#  match '/calendar_elems/:id(/:year(/:month))' => 'calendar_elems#show', :as => :calendar_elems, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  #  end

  # Elements resources
  match ':shortcut/:position/new_element' => 'templates#new_element', :as => :new_element

  # shortcut usage
  match ':shortcut' => 'templates#show', :as => :shortcut
  match 'admin/:shortcut' => 'templates#edit', :as => :admin_shortcut
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :calendar_elem

  has_event_calendar

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :get_template


  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new(:color => @calendar_elem.event_color)
  end


  def edit
    @event = Event.find(params[:id])
  end


  def create
    @event = Event.new(params[:event])
    if @event.save and @calendar_elem.events << @event
      redirect_to(@calendar_elem, :notice => 'Event was successfully added.')
    else
      render :action => "new"
    end
  end


  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to(@calendar_elem, :notice => 'Event was successfully updated.')
    else
      render :action => "edit"
    end
  end


  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to(calendar_elem_url(@calendar_elem), :notice => 'Event was successfully destroyed.')
  end




  private
  def get_template
    if params[:calendar_elem_id]
      @calendar_elem = CalendarElem.find(params[:calendar_elem_id])
      @node = @calendar_elem.element.template.node
    end
    super
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% event = locals[:event] %>

<p>
  <b>Name:</b>
  <%= event.name %>
</p>

<p>
  <b>Start at:</b>
  <%= event.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= event.end_at %>
</p>

<p>
  <b>All day:</b>
  <%= event.all_day %>
</p>

<p>
  <b>Color:</b>
  <%= event.color %>
</p>

<% if event.calendar_elem and event.calendar_elem.display_title %>
  <p>
    <b>Calendar: </b>
    <%= event.calendar_elem.title %>
  </p>
<% end %>

app/views/events/_form.html.erb
<%= form_for([@calendar_elem, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.check_box :all_day %> &nbsp;
    <%= f.label :all_day %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.select :color, color_select %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form'%>

<%= link_to 'Cancel', calendar_elem_path(@calendar_elem) %>

app/views/events/new.html.erb
<h1>Add Event</h1>

<%= render 'form' %>

<%= link_to 'Cancel', calendar_elem_path(@calendar_elem) %>

app/views/events/show.html.erb
<%= render 'event', :locals => {:event => @event} %>

<%= admin_area do %>
  <p>
    | <%= link_to 'Back to Calendar', calendar_elem_path(@calendar_elem) %> |
    <%= link_to 'Edit Event', edit_calendar_elem_event_path(@calendar_elem, @event) %> |
    <%= link_to 'Destroy Event', calendar_elem_event_path(@calendar_elem, @event), :confirm => 'Are you sure?', :method => :delete %> |
  </p>
<% end %>